### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by jpr105** [melmorabity/tv_grab_fr_sfr#1]
Bonjour,

En fait je ne voulais pas signaler un dysfonctionnement mais simplement vous remercier pour vos deux programmes "tv_grab_fr_sfr" et "tv_grab_fr_telerama" que j'ai utilisé et adapté pour un environnement XMLTV / DVBLOGIC / NAS SYNOLOGY.

Cela fonctionne à merveille, merci encore.

Cordialement

**Comment by melmorabity** [comment]
Merci pour ton retour, ça fait plaisir :-)
